# vStack test config
system:
  system: dgx-attacc
  gpu: A100a
  ngpu: 8

pim:
  pim: bank
  die_type: vstack
  compute_stack_l1: 4
  capacity_stack_l2: 4
  powerlimit: false
  ffopt: false
  pipeopt: false

model:
  model: GPT-175B
  word: 2

workload:
  mode: fixed
  lin: 2048
  lout: 128
  batch: 1

kv_arch:
  num_cards: 8
  host_kv_total_gb: 512
  dma_bandwidth_gbps: 1676
  pcie_bandwidth_gbps: 64
